

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: GH issues to items csv

on:
  issues:
    types: [opened, edited]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygithub
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Checkout gh-pages branch
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.rebase false
          git fetch
          git checkout -b "gh-pages"
          git pull origin "gh-pages" --allow-unrelated-histories
          git checkout -b "main"
    - name: Run gh-issues.py
      env:
        Token: ${{ secrets.GITHUB_TOKEN }}
      run: python gh-issues.py
    - name: commit changes back to repository
      run: |
          date > generated.txt
          git checkout -b "gh-pages"
          git add store-csvs/*
          git commit -m "generated"
          git push -u origin "gh-pages"

